### ISSUE TITLE
Am I missing the obvious? (cargo build/run integration)

### ISSUE THREAD

**Issue by MagaTailor** [pegasos1/cargo-profiler#2]
Do you still have to manually build the binary you wish to profile with e.g. `cargo build`?

I mean, if a Cargo.toml exists I'd expect the following to work:

`cargo profiler  callgrind` or `cargo --release profiler  callgrind`

**Comment by petevine** [comment]
I mean, if a Cargo.toml exists I'd expect the following to work:

`cargo profiler  callgrind` or `cargo --release profiler  callgrind`

**Comment by MagaTailor** [comment]
BTW, profiler prints nothing after interrupting with `Ctrl+C`.

**Comment by regexident** [comment]
I'd expect it to be ordered like this `cargo profiler callgrind --release` but have to agree on the general thought.

**Comment by MagaTailor** [comment]
@regexident Right, I meant `profiler --release`, the original syntax isn't even valid in cargo.

**Comment by kernelmachine** [comment]
Ah my bad, can't believe I missed that. Should get that implemented.

**Comment by kernelmachine** [comment]
This is in the works, should be up by tomorrow.

**Comment by regexident** [comment]
Bonus points for also supporting `cargo profiler callgrind --release -- --some=thing -v --flag`, which would then pass over `--some=thing -v --flag` to the running executable. 💯 *cough*

**Comment by kernelmachine** [comment]
yep, this was referenced in #7. The open PR #12  addresses most of the issues. all that needs to be addressed is binary arguments as well as custom output directories, and we're golden. seems like people are looking for similar improvements, which is good.

**Comment by kernelmachine** [comment]
This is available in v0.1.3. Closing this issue, as #7 references binary arguments which still remains an open issue.

**Comment by MagaTailor** [comment]
Thanks @pegasos1, beginning to look really great! Two issues:
- compilation is hidden, `--verbose` can't be passed to cargo in any position
- building and running examples, normally via `cargo run --example some_example`, doesn't work yet - we're already running binaries, so maybe, for super tight integration, profiler could check for available examples and build the one passed to it, like `cargo profiler callgrind some_example` ?

Even though it's a different issue, my 2nd [comment](https://github.com/pegasos1/cargo-profiler/issues/2#issuecomment-218676476) is a much more serious problem at the moment. Not all programmes terminate naturally or it can be impractical to wait that long.

**Comment by kernelmachine** [comment]
@petevine, I'm going to open up some new issues addressing these, they should be fairly straightforward to implement. Thanks so much for pointing these out! 

Also, completely overlooked the comment. Do you know if there's currently a way to catch `Ctrl +C` via std? I found [this ](https://github.com/BurntSushi/chan-signal) crate that could help us do this, as well as [this ](https://users.rust-lang.org/t/unix-signals-in-rust/733/3) conversation.

**Comment by kernelmachine** [comment]
You can check out/comment on #14 #15 #16

**Comment by MagaTailor** [comment]
Not sure about a cross-platform std solution - from the links you provided it seems it's still WIP. But on *nix you should be fine using @burntsushi's crate.

Also e.g. parity [uses](https://github.com/ethcore/parity/blob/2b78e511c9e08af9647d91cf6e8718900c753a55/parity/main.rs#248) the [ctrlc](https://github.com/Detegr/rust-ctrlc) crate.
