### ISSUE TITLE
Failure info not passed to profiler 

### ISSUE THREAD

**Issue by MagaTailor** [pegasos1/cargo-profiler#20]
``` shell
$ cargo profiler callgrind --bin ./prime++

Profiling prime with callgrind...

Total Instructions...0
```

Two issue again ;)
- We're inside a rust project named `prime` but profiling a C++ `prime++` binary - what happened to the two pluses in the displayed name? (probably integration related)
- We're given no info about the failure whereas the first/last lines from valgrind output reveal the problem:

```
==6072==     Valgrind's memory management: out of memory:
==6072==     Whatever the reason, Valgrind cannot continue.  Sorry.
```

**Comment by kernelmachine** [comment]
Interesting. Thanks for submitting - going to look at this later this evening.

**Comment by kernelmachine** [comment]
By the way, I wonder if there's a good way to produce unit tests around cargo profiler to identify these unexpected errors. Difficult to get coverage so far. Not sure if it's possible.

**Comment by kernelmachine** [comment]
valgrind failures can now propagate to cargo profiler in v0.1.4. Now it's a matter of catching different valgrind crashes, so far I have the 'out of memory'  msg propagated. Let me know if you come across others.

**Comment by MagaTailor** [comment]
What about profiling inside cargo-profiler directory?

``` shell
$ cargo profiler callgrind 

Compiling cargo-profiler in debug mode...

Profiling cargo-profiler with callgrind...
error: Regex error -- please file a bug. In bug report, please include the original output file from profiler, e.g. from valgrind --tool=cachegrind --cachegrind-out-file=cachegrind.txt
error: third party subcommand `cargo-profiler` exited unsuccessfully
```

[callgrind.txt](https://github.com/pegasos1/cargo-profiler/files/276594/callgrind.txt)

For some reason `cargo profiler callgrind --release` doesn't work:

```
 Compiling cargo-profiler in release mode...
error: Failed to compile cargo-profiler.

error: no such subcommand

error: third party subcommand `cargo-profiler` exited unsuccessfully
```

**Comment by kernelmachine** [comment]
That's strange. both callgrind and callgrind --release work for me in the cargo-profiler directory. are you sure you don't have any cargo-profiler conflicts? Do these errors only happen in the cargo-profiler directory?

**Comment by MagaTailor** [comment]
It seems it's broken like this everywhere; no idea what's going on, maybe compiling with `-Z orbit` broke some code.

**Comment by kernelmachine** [comment]
Yeah don't know either, your callgrind.txt is parsing fine on my machine. 

```
fn test_callgrind_parse() {
        let test_file = "callgrind.txt";
        let callgrind_output = Command::new("callgrind_annotate")
                                    .arg(test_file)
                                    .output()
                                    .unwrap_or_else(|e| panic!("failed to execute process: {}", e));
        let cli_out = String::from_utf8(callgrind_output.stdout)
                          .expect("error while returning callgrind stdout");
        let profiler = Profiler::new_callgrind();
        let parsed = profiler.callgrind_parse(&cli_out, 10);
        println!("{:?}", parsed);
    }
```

returns

```
Ok(CallGrind { total_instructions: 895156, instructions: [84753, 55269, 47785, 34237, 33775, 30926, 27927, 24015, 22721, 22650], functs: ["dl-lookup.c:do_lookup_x", "vfscanf.c:_IO_vfscanf", "dl-addr.c:_dl_addr", "memset.S:memset", "dl-lookup.c:_dl_lookup_symbol_x", "dl-machine.h:_dl_relocate_object", "???:__udivsi3", "strtol_l.c:____strtoul_l_internal", "strcmp.c:strcmp\'2", "memcpy_impl.S:__memcpy_neon"] })
```

**Comment by MagaTailor** [comment]
No difference, mir or no mir, even at `opt-level=2` I'm getting a broken profiler. I'll try a different rustc version, otherwise it could be an ARM specific problem.

**Comment by kernelmachine** [comment]
any clues yet?

**Comment by MagaTailor** [comment]
I tried using rustc 1.8 stable but it made no difference either. Maybe it's a problem with cargo interactions - any particular version requirements there?  

More verbose errors could really help.

**Comment by MagaTailor** [comment]
And besides, the original issue still persists (minus the changed binary name):

```
cargo profiler callgrind --bin ./prime++

Profiling prime++ with callgrind...

Total Instructions...0
```

Could my valgrind (3.12 SVN on ARM) be too new or otherwise problematic?

**Comment by kernelmachine** [comment]
Can you submit the output of valgrind --tool=cachegrind --cachegrind-out-file=cachegrind.txt ./prime++? Just need to test the regex on it.

**Comment by MagaTailor** [comment]
Cachegrind is not a problem, did you mean callgrind?

I'm attaching redirected output from callgrind (it doesn't finish normally so the `-out-file` ends up empty)
[callgrind.txt](https://github.com/pegasos1/cargo-profiler/files/281512/callgrind.txt)
