### ISSUE TITLE
Recent cargo integration broken?

### ISSUE THREAD

**Issue by MagaTailor** [pegasos1/cargo-profiler#22]
Continuing from #20, it seems running the same binary via `--bin` works as expected, whereas `cargo profiler callgrind` is able to compile but fails in `debug` mode and doesn't even build in `release`.

I'm going to use an older cargo binary to see if that helps.

**Comment by MagaTailor** [comment]
No, it wasn't relevant. Finally, I tried a `cargo install cargo-profiler --vers 0.1.3`, but it installed a `0.1.4` anyway and surprisingly `release` integration seems to work in one simple rust project. In projects like `exa` or `cargo-profiler`, the first comment still stands but `debug` started producing profiles.

No idea what's going on here.

**Comment by kernelmachine** [comment]
Hey @petevine - sorry you're dealing with these issues. I just wrote a patch in v0.1.5 that should fix the  compilation issues, let me know if you can compile and run properly now!

**Comment by kernelmachine** [comment]
Thanks again for submitting these issues, hopefully things should stabilize asap.

**Comment by MagaTailor** [comment]
Yup, that part is fixed. Thx!
