### ISSUE TITLE
arg passing to the program being benchmarked not working

### ISSUE THREAD

**Issue by osa1** [pegasos1/cargo-profiler#25]
I have this program:

``` rust
use std::thread;
use std::time::Duration;
use std::env;
fn main() {
    env::args().nth(1).unwrap();
    thread::sleep(Duration::new(100000, 0));
}
```

It should hang for a long time when it takes at least one command line argument. But when I run it like this it terminates in an instant:

```
$ cargo profiler callgrind --bin ./target/release/flow -- arg1 arg2 arg3 arg4
```

**Comment by akiradeveloper** [comment]
This is really working?

`cargo profiler callgrind --release -n20 -- 1 1`

This command finishes instantly.
