### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by rockstar** [pegasos1/cargo-profiler#39]
The last commit shows more than a year ago. There is an open and unresponsive PR. There are issues that have been filed and not responded to. Is this project still maintained, or should I find another tool to use?

**Comment by svenstaro** [comment]
I guess that answers the question. @kernelmachine would you consider adding more contributors that can also make crates.io releases?

**Comment by kernelmachine** [comment]
@rockstar I'm not actively maintaining this project, and happy to hand it off. @svenstaro has explicitly requested being a contributor. Feel free to add others as you see fit.

**Comment by kernelmachine** [comment]
@svenstaro added you as a collaborator on the project, let me know if you've got full reins.

**Comment by svenstaro** [comment]
Thanks! Keep in mind that normal contributors still can't change stuff such as API keys (for instance for CI) and you might get bothered for that again when the need comes up. Alternatively, you could transfer the repo to one of the new contributors if you don't want to be bothered now and then.

Also, could you add me to the crate on crates.io? Same username on there. Without that, we can't publish new versions.

**Comment by kernelmachine** [comment]
Sure, I'll transfer the repo to you so you have full access. I've also sent you an invite to the crate on crates.io.

**Comment by svenstaro** [comment]
Sweet, thanks a lot! I'll take good care of it. I accepted the transfer and the ownership request on crates.io.

**Comment by svenstaro** [comment]
Well, now it's maintained! Closing.
